-- FitForge Indian Food Database seed
-- 200+ curated items. Nutrition values are PER SERVING (not per 100g).
-- Macros based on IFCT-2017 reference ranges + common recipe estimates.
-- Paste this entire file into the Supabase SQL editor.

INSERT INTO food_database
  (name, name_hindi, category, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, serving_size, serving_unit, serving_description, is_combo, is_indian, source)
VALUES
-- ─────────────────────────────────────────────────────────────────────────────
-- BREAKFAST  (30)
-- ─────────────────────────────────────────────────────────────────────────────
('Poha',                       'पोहा',                'breakfast', 250, 6.0,  42.0, 7.0,  3.0, 1, 'plate',  '1 plate poha (~150g cooked)',                  false, true, 'IFCT-2017'),
('Upma',                       'उपमा',                'breakfast', 230, 6.0,  38.0, 6.5,  2.5, 1, 'plate',  '1 plate upma (~150g cooked)',                  false, true, 'IFCT-2017'),
('Idli',                       'इडली',                'breakfast', 130, 4.0,  26.0, 1.0,  1.5, 2, 'piece',  '2 medium idlis',                               false, true, 'IFCT-2017'),
('Dosa plain',                 'सादा डोसा',           'breakfast', 120, 3.0,  20.0, 3.5,  1.0, 1, 'piece',  '1 plain dosa',                                 false, true, 'IFCT-2017'),
('Masala dosa',                'मसाला डोसा',          'breakfast', 250, 5.5,  38.0, 9.0,  3.0, 1, 'piece',  '1 masala dosa with aloo filling',              false, true, 'IFCT-2017'),
('Paratha plain',              'सादा पराठा',          'breakfast', 200, 5.0,  28.0, 8.0,  2.5, 1, 'piece',  '1 plain paratha (~50g atta)',                  false, true, 'IFCT-2017'),
('Aloo paratha',               'आलू पराठा',           'breakfast', 300, 6.0,  40.0, 12.0, 3.5, 1, 'piece',  '1 aloo paratha with ghee',                     false, true, 'IFCT-2017'),
('Paneer paratha',             'पनीर पराठा',          'breakfast', 320, 10.0, 35.0, 16.0, 3.0, 1, 'piece',  '1 paneer paratha',                             false, true, 'IFCT-2017'),
('Gobi paratha',               'गोभी पराठा',          'breakfast', 270, 6.5,  35.0, 11.0, 4.0, 1, 'piece',  '1 gobi paratha',                               false, true, 'IFCT-2017'),
('Methi paratha',              'मेथी पराठा',          'breakfast', 240, 6.0,  32.0, 10.0, 4.0, 1, 'piece',  '1 methi paratha',                              false, true, 'IFCT-2017'),
('Besan chilla',               'बेसन चीला',           'breakfast', 150, 8.0,  16.0, 6.0,  3.0, 1, 'piece',  '1 besan chilla',                               false, true, 'IFCT-2017'),
('Moong dal chilla',           'मूँग दाल चीला',       'breakfast', 120, 9.0,  14.0, 3.0,  3.5, 1, 'piece',  '1 moong dal chilla',                           false, true, 'IFCT-2017'),
('Thepla',                     'थेपला',               'breakfast', 130, 4.0,  18.0, 5.0,  2.0, 1, 'piece',  '1 methi thepla',                               false, true, 'IFCT-2017'),
('Medu vada',                  'मेदु वड़ा',            'breakfast', 200, 7.0,  24.0, 9.0,  2.5, 2, 'piece',  '2 medu vadas',                                 false, true, 'IFCT-2017'),
('Sabudana khichdi',           'साबूदाना खिचड़ी',      'breakfast', 280, 4.5,  46.0, 9.0,  2.0, 1, 'plate',  '1 plate sabudana khichdi',                     false, true, 'IFCT-2017'),
('Cornflakes with milk',       'कॉर्नफ्लेक्स दूध के साथ', 'breakfast', 200, 7.0,  35.0, 4.0,  1.5, 1, 'bowl',   '1 bowl cornflakes with toned milk',            false, true, 'estimate'),
('Oats porridge',              'ओट्स दलिया',          'breakfast', 180, 7.0,  28.0, 4.0,  4.5, 1, 'bowl',   '1 bowl oats with milk',                        false, true, 'estimate'),
('Bread butter jam',           'ब्रेड मक्खन जैम',     'breakfast', 250, 6.0,  38.0, 9.0,  1.5, 2, 'slice',  '2 slices white bread with butter & jam',       false, true, 'estimate'),
('Veg sandwich',               'वेज सैंडविच',         'breakfast', 200, 6.0,  28.0, 7.0,  3.0, 1, 'piece',  '1 grilled veg sandwich',                       false, true, 'estimate'),
('Egg bhurji',                 'अंडा भुर्जी',         'breakfast', 180, 13.0, 3.0,  13.0, 0.5, 2, 'piece',  '2 eggs scrambled with onion-tomato',           false, true, 'IFCT-2017'),
('Boiled eggs',                'उबले अंडे',           'breakfast', 156, 13.0, 1.2,  10.0, 0.0, 2, 'piece',  '2 boiled whole eggs',                          false, true, 'IFCT-2017'),
('Anda bhurji with bread',     'अंडा भुर्जी ब्रेड के साथ', 'breakfast', 330, 17.0, 30.0, 16.0, 1.5, 1, 'plate',  '2 eggs bhurji + 2 bread slices',               true,  true, 'estimate'),
('Banana peanut butter smoothie','केला पीनट बटर स्मूदी', 'breakfast', 300, 11.0, 38.0, 12.0, 3.0, 1, 'glass',  '1 glass banana + peanut butter + milk',        false, true, 'estimate'),
('Muesli with curd',           'मूसली दही के साथ',    'breakfast', 250, 9.0,  40.0, 6.0,  4.0, 1, 'bowl',   '1 bowl muesli with curd',                      false, true, 'estimate'),
('Chole bhature',              'छोले भटूरे',          'breakfast', 550, 14.0, 72.0, 22.0, 8.0, 1, 'plate',  '2 bhature + 1 katori chole',                   true,  true, 'IFCT-2017'),
('Puri bhaji',                 'पूरी भाजी',           'breakfast', 400, 7.5,  50.0, 18.0, 4.0, 1, 'plate',  '2 puris + aloo sabzi',                         true,  true, 'IFCT-2017'),
('Bread omelette',             'ब्रेड ऑमलेट',         'breakfast', 350, 17.0, 30.0, 18.0, 1.5, 1, 'plate',  '2 bread + 2 egg omelette',                     true,  true, 'estimate'),
('Pesarattu',                  'पेसरट्टू',            'breakfast', 180, 10.0, 24.0, 4.0,  4.0, 1, 'piece',  '1 green-gram dosa',                            false, true, 'IFCT-2017'),
('Uttapam',                    'उत्तपम',              'breakfast', 180, 5.0,  28.0, 5.0,  1.5, 1, 'piece',  '1 onion-tomato uttapam',                       false, true, 'IFCT-2017'),
('Aloo poori',                 'आलू पूरी',            'breakfast', 420, 8.0,  52.0, 19.0, 4.0, 1, 'plate',  '2 puri + aloo sabzi',                          true,  true, 'estimate'),

-- ─────────────────────────────────────────────────────────────────────────────
-- DAL / SABZI / CURRIES  (35)
-- ─────────────────────────────────────────────────────────────────────────────
('Dal tadka',                  'दाल तड़का',            'dal_sabzi', 150, 9.0,  20.0, 4.0,  5.0, 1, 'katori', '1 katori arhar dal tadka',                     false, true, 'IFCT-2017'),
('Dal fry',                    'दाल फ्राई',            'dal_sabzi', 160, 9.0,  20.0, 5.0,  5.0, 1, 'katori', '1 katori dal fry',                             false, true, 'IFCT-2017'),
('Dal makhani',                'दाल मखनी',            'dal_sabzi', 220, 9.0,  22.0, 11.0, 6.0, 1, 'katori', '1 katori dal makhani',                         false, true, 'IFCT-2017'),
('Rajma',                      'राजमा',               'dal_sabzi', 180, 10.0, 26.0, 4.0,  7.5, 1, 'katori', '1 katori rajma curry',                         false, true, 'IFCT-2017'),
('Chole / Chana masala',       'छोले',                'dal_sabzi', 200, 9.0,  28.0, 6.0,  7.0, 1, 'katori', '1 katori chole curry',                         false, true, 'IFCT-2017'),
('Sambhar',                    'सांबर',               'dal_sabzi', 130, 6.5,  18.0, 3.5,  4.5, 1, 'katori', '1 katori sambhar with vegetables',             false, true, 'IFCT-2017'),
('Rasam',                      'रसम',                 'dal_sabzi', 50,  2.0,  8.0,  1.5,  1.0, 1, 'katori', '1 katori rasam',                               false, true, 'IFCT-2017'),
('Kadhi pakora',               'कढ़ी पकोड़ा',           'dal_sabzi', 180, 6.0,  18.0, 9.0,  1.5, 1, 'katori', '1 katori kadhi with pakoras',                  false, true, 'IFCT-2017'),
('Aloo gobi',                  'आलू गोभी',            'dal_sabzi', 150, 4.0,  20.0, 7.0,  4.0, 1, 'katori', '1 katori aloo gobi sabzi',                     false, true, 'IFCT-2017'),
('Aloo matar',                 'आलू मटर',             'dal_sabzi', 160, 5.0,  22.0, 6.0,  4.0, 1, 'katori', '1 katori aloo matar sabzi',                    false, true, 'IFCT-2017'),
('Bhindi masala',              'भिंडी मसाला',         'dal_sabzi', 120, 3.0,  14.0, 7.0,  4.0, 1, 'katori', '1 katori bhindi masala',                       false, true, 'IFCT-2017'),
('Baingan bharta',             'बैंगन भरता',          'dal_sabzi', 130, 3.0,  14.0, 8.0,  5.0, 1, 'katori', '1 katori baingan bharta',                      false, true, 'IFCT-2017'),
('Palak paneer',               'पालक पनीर',           'dal_sabzi', 230, 12.0, 10.0, 16.0, 3.5, 1, 'katori', '1 katori palak paneer',                        false, true, 'IFCT-2017'),
('Shahi paneer',               'शाही पनीर',           'dal_sabzi', 280, 11.0, 14.0, 20.0, 1.5, 1, 'katori', '1 katori shahi paneer',                        false, true, 'IFCT-2017'),
('Matar paneer',               'मटर पनीर',            'dal_sabzi', 240, 12.0, 14.0, 15.0, 3.0, 1, 'katori', '1 katori matar paneer',                        false, true, 'IFCT-2017'),
('Paneer butter masala',       'पनीर बटर मसाला',      'dal_sabzi', 300, 13.0, 14.0, 22.0, 1.5, 1, 'katori', '1 katori paneer butter masala',                false, true, 'IFCT-2017'),
('Kadai paneer',               'कड़ाही पनीर',          'dal_sabzi', 260, 13.0, 12.0, 18.0, 2.0, 1, 'katori', '1 katori kadai paneer',                        false, true, 'IFCT-2017'),
('Malai kofta',                'मलाई कोफ्ता',         'dal_sabzi', 320, 8.0,  20.0, 23.0, 2.0, 2, 'piece',  '2 koftas with gravy',                          false, true, 'IFCT-2017'),
('Mixed veg',                  'मिक्स वेज',           'dal_sabzi', 120, 3.0,  14.0, 6.0,  4.0, 1, 'katori', '1 katori mixed veg sabzi',                     false, true, 'IFCT-2017'),
('Lauki sabzi',                'लौकी सब्ज़ी',          'dal_sabzi', 80,  2.0,  10.0, 4.0,  2.5, 1, 'katori', '1 katori lauki sabzi',                         false, true, 'IFCT-2017'),
('Tinda sabzi',                'टिंडा सब्ज़ी',         'dal_sabzi', 90,  2.5,  10.0, 5.0,  3.0, 1, 'katori', '1 katori tinda sabzi',                         false, true, 'IFCT-2017'),
('Chana dal',                  'चना दाल',             'dal_sabzi', 170, 10.0, 24.0, 4.0,  6.0, 1, 'katori', '1 katori chana dal',                           false, true, 'IFCT-2017'),
('Moong dal',                  'मूँग दाल',            'dal_sabzi', 140, 9.0,  20.0, 3.0,  5.0, 1, 'katori', '1 katori moong dal',                           false, true, 'IFCT-2017'),
('Masoor dal',                 'मसूर दाल',            'dal_sabzi', 150, 9.0,  22.0, 3.5,  5.5, 1, 'katori', '1 katori masoor dal',                          false, true, 'IFCT-2017'),
('Mix dal (panchmel)',         'पंचमेल दाल',          'dal_sabzi', 165, 9.5,  22.0, 4.5,  5.5, 1, 'katori', '1 katori mixed dal',                           false, true, 'IFCT-2017'),
('Chicken curry',              'चिकन करी',            'dal_sabzi', 250, 25.0, 8.0,  14.0, 1.0, 1, 'katori', '1 katori chicken curry (~150g)',               false, true, 'IFCT-2017'),
('Butter chicken',             'बटर चिकन',            'dal_sabzi', 320, 22.0, 10.0, 22.0, 1.0, 1, 'katori', '1 katori butter chicken',                      false, true, 'IFCT-2017'),
('Chicken tikka masala',       'चिकन टिक्का मसाला',   'dal_sabzi', 280, 24.0, 9.0,  18.0, 1.5, 1, 'katori', '1 katori chicken tikka masala',                false, true, 'IFCT-2017'),
('Egg curry',                  'अंडा करी',            'dal_sabzi', 250, 14.0, 8.0,  18.0, 1.0, 2, 'piece',  '2 egg curry with gravy',                       false, true, 'IFCT-2017'),
('Mutton curry',               'मटन करी',             'dal_sabzi', 300, 22.0, 6.0,  22.0, 0.8, 1, 'katori', '1 katori mutton curry',                        false, true, 'IFCT-2017'),
('Fish curry',                 'मछली करी',            'dal_sabzi', 200, 22.0, 6.0,  10.0, 0.8, 1, 'piece',  '1 fish piece with gravy',                      false, true, 'IFCT-2017'),
('Keema matar',                'कीमा मटर',            'dal_sabzi', 270, 20.0, 10.0, 17.0, 2.5, 1, 'katori', '1 katori keema with peas',                     false, true, 'IFCT-2017'),
('Gobi matar',                 'गोभी मटर',            'dal_sabzi', 130, 4.0,  16.0, 6.0,  4.5, 1, 'katori', '1 katori gobi matar sabzi',                    false, true, 'IFCT-2017'),
('Karela sabzi',               'करेला सब्ज़ी',         'dal_sabzi', 110, 2.5,  12.0, 6.0,  3.5, 1, 'katori', '1 katori karela sabzi',                        false, true, 'IFCT-2017'),
('Saag (mustard)',             'सरसों का साग',        'dal_sabzi', 160, 5.0,  12.0, 10.0, 4.0, 1, 'katori', '1 katori sarson ka saag',                      false, true, 'IFCT-2017'),

-- ─────────────────────────────────────────────────────────────────────────────
-- ROTI / RICE / BREAD  (22)
-- ─────────────────────────────────────────────────────────────────────────────
('Chapati',                    'चपाती',               'roti_rice', 120, 3.0,  20.0, 3.5,  2.0, 1, 'piece',  '1 medium chapati (~30g atta)',                 false, true, 'IFCT-2017'),
('Phulka',                     'फुलका',               'roti_rice', 70,  2.0,  14.0, 0.5,  1.5, 1, 'piece',  '1 phulka without ghee',                        false, true, 'IFCT-2017'),
('Tandoori roti',              'तंदूरी रोटी',         'roti_rice', 120, 3.5,  22.0, 1.5,  2.5, 1, 'piece',  '1 tandoori roti',                              false, true, 'IFCT-2017'),
('Rumali roti',                'रूमाली रोटी',         'roti_rice', 150, 4.0,  28.0, 2.5,  1.5, 1, 'piece',  '1 large rumali roti',                          false, true, 'IFCT-2017'),
('Missi roti',                 'मिस्सी रोटी',         'roti_rice', 140, 5.0,  22.0, 4.0,  3.5, 1, 'piece',  '1 missi roti (wheat + besan)',                 false, true, 'IFCT-2017'),
('Naan plain',                 'सादा नान',            'roti_rice', 260, 7.0,  45.0, 5.5,  2.0, 1, 'piece',  '1 plain naan',                                 false, true, 'IFCT-2017'),
('Butter naan',                'बटर नान',             'roti_rice', 310, 7.0,  45.0, 11.0, 2.0, 1, 'piece',  '1 butter naan',                                false, true, 'IFCT-2017'),
('Garlic naan',                'लहसुन नान',           'roti_rice', 300, 7.5,  44.0, 10.0, 2.0, 1, 'piece',  '1 garlic naan',                                false, true, 'IFCT-2017'),
('Plain paratha with ghee',    'सादा पराठा',          'roti_rice', 200, 5.0,  28.0, 8.0,  2.5, 1, 'piece',  '1 plain paratha with ghee',                    false, true, 'IFCT-2017'),
('Bajra roti',                 'बाजरा रोटी',          'roti_rice', 120, 3.5,  20.0, 3.0,  3.0, 1, 'piece',  '1 bajra roti',                                 false, true, 'IFCT-2017'),
('Jowar roti',                 'ज्वार रोटी',          'roti_rice', 100, 3.0,  20.0, 1.5,  3.5, 1, 'piece',  '1 jowar roti',                                 false, true, 'IFCT-2017'),
('Ragi roti',                  'रागी रोटी',           'roti_rice', 110, 3.0,  22.0, 1.5,  4.0, 1, 'piece',  '1 ragi roti',                                  false, true, 'IFCT-2017'),
('White rice cooked',          'सादा चावल',           'roti_rice', 180, 3.5,  40.0, 0.4,  0.6, 150,'g',     '150g cooked basmati / sona-masuri rice',       false, true, 'IFCT-2017'),
('Brown rice cooked',          'ब्राउन चावल',         'roti_rice', 170, 4.0,  36.0, 1.5,  2.0, 150,'g',     '150g cooked brown rice',                       false, true, 'IFCT-2017'),
('Jeera rice',                 'जीरा चावल',           'roti_rice', 220, 4.0,  40.0, 5.0,  1.0, 1, 'plate',  '1 plate jeera rice',                           false, true, 'IFCT-2017'),
('Veg pulao',                  'वेज पुलाव',           'roti_rice', 250, 5.5,  42.0, 7.0,  2.5, 1, 'plate',  '1 plate veg pulao',                            false, true, 'IFCT-2017'),
('Chicken biryani',            'चिकन बिरयानी',        'roti_rice', 450, 22.0, 58.0, 14.0, 2.0, 1, 'plate',  '1 plate chicken biryani (~300g)',              false, true, 'IFCT-2017'),
('Veg biryani',                'वेज बिरयानी',         'roti_rice', 350, 7.0,  55.0, 12.0, 3.0, 1, 'plate',  '1 plate veg biryani',                          false, true, 'IFCT-2017'),
('Khichdi',                    'खिचड़ी',               'roti_rice', 200, 7.0,  35.0, 3.5,  3.0, 1, 'plate',  '1 plate moong dal khichdi',                    false, true, 'IFCT-2017'),
('Lemon rice',                 'लेमन राइस',           'roti_rice', 230, 4.5,  42.0, 5.5,  1.5, 1, 'plate',  '1 plate lemon rice',                           false, true, 'IFCT-2017'),
('Curd rice',                  'दही चावल',            'roti_rice', 220, 7.0,  38.0, 4.5,  1.0, 1, 'plate',  '1 plate curd rice',                            false, true, 'IFCT-2017'),
('Tomato rice',                'टमाटर चावल',          'roti_rice', 240, 5.0,  44.0, 5.0,  2.0, 1, 'plate',  '1 plate tomato rice',                          false, true, 'IFCT-2017'),

-- ─────────────────────────────────────────────────────────────────────────────
-- COMBO MEALS  (25)  — is_combo = true
-- ─────────────────────────────────────────────────────────────────────────────
('Dal chawal',                 'दाल चावल',            'combo',     330, 12.5, 60.0, 4.4,  5.6, 1, 'plate',  '1 katori dal + 1 plate rice',                  true,  true, 'composite'),
('Rajma chawal',               'राजमा चावल',          'combo',     360, 13.5, 66.0, 4.4,  8.1, 1, 'plate',  '1 katori rajma + 1 plate rice',                true,  true, 'composite'),
('Chole chawal',               'छोले चावल',           'combo',     380, 12.5, 68.0, 6.4,  7.6, 1, 'plate',  '1 katori chole + 1 plate rice',                true,  true, 'composite'),
('Kadhi chawal',               'कढ़ी चावल',            'combo',     360, 9.5,  58.0, 9.4,  2.1, 1, 'plate',  '1 katori kadhi + 1 plate rice',                true,  true, 'composite'),
('Sambhar rice',               'सांबर चावल',          'combo',     310, 10.0, 58.0, 3.9,  5.1, 1, 'plate',  '1 katori sambhar + 1 plate rice',              true,  true, 'composite'),
('Dal roti',                   'दाल रोटी',            'combo',     390, 15.0, 60.0, 11.0, 9.0, 1, 'plate',  '1 katori dal + 2 roti',                        true,  true, 'composite'),
('Sabzi roti',                 'सब्ज़ी रोटी',          'combo',     360, 9.0,  54.0, 13.0, 8.0, 1, 'plate',  '1 katori mixed sabzi + 2 roti',                true,  true, 'composite'),
('Rajma roti',                 'राजमा रोटी',          'combo',     420, 16.0, 66.0, 11.0, 11.5,1, 'plate',  '1 katori rajma + 2 roti',                      true,  true, 'composite'),
('Chole roti',                 'छोले रोटी',           'combo',     440, 15.0, 68.0, 13.0, 11.0,1, 'plate',  '1 katori chole + 2 roti',                      true,  true, 'composite'),
('Paneer sabzi roti',          'पनीर रोटी',           'combo',     470, 18.0, 54.0, 22.0, 5.5, 1, 'plate',  '1 katori paneer sabzi + 2 roti',               true,  true, 'composite'),
('Chicken curry rice',         'चिकन चावल',           'combo',     430, 28.5, 48.0, 14.4, 1.6, 1, 'plate',  '1 katori chicken curry + 1 plate rice',        true,  true, 'composite'),
('Chicken curry roti',         'चिकन रोटी',           'combo',     490, 31.0, 48.0, 21.0, 5.0, 1, 'plate',  '1 katori chicken curry + 2 roti',              true,  true, 'composite'),
('Egg curry rice',             'अंडा चावल',           'combo',     430, 17.5, 48.0, 18.4, 1.6, 1, 'plate',  '2 egg curry + 1 plate rice',                   true,  true, 'composite'),
('Mutton curry rice',          'मटन चावल',            'combo',     480, 25.5, 46.0, 22.4, 1.4, 1, 'plate',  '1 katori mutton curry + 1 plate rice',         true,  true, 'composite'),
('Fish curry rice',            'मछली चावल',           'combo',     380, 25.5, 46.0, 10.4, 1.4, 1, 'plate',  '1 fish curry + 1 plate rice',                  true,  true, 'composite'),
('Butter chicken with naan',   'बटर चिकन नान',        'combo',     580, 29.0, 55.0, 27.5, 3.0, 1, 'plate',  '1 katori butter chicken + 1 naan',             true,  true, 'composite'),
('Paneer butter masala naan',  'पनीर बटर मसाला नान',  'combo',     560, 20.0, 59.0, 27.5, 3.5, 1, 'plate',  '1 katori paneer butter masala + 1 naan',       true,  true, 'composite'),
('South Indian thali veg',     'दक्षिण भारतीय थाली',  'combo',     300, 11.0, 46.0, 8.0,  6.0, 1, 'plate',  '2 idli + sambhar + chutney',                   true,  true, 'composite'),
('North Indian thali veg',     'उत्तर भारतीय थाली',   'combo',     550, 18.0, 80.0, 18.0, 11.0,1, 'plate',  '2 roti + dal + sabzi + rice + salad',          true,  true, 'composite'),
('North Indian thali non-veg', 'नॉन-वेज थाली',        'combo',     650, 32.0, 80.0, 23.0, 9.0, 1, 'plate',  '2 roti + chicken curry + dal + rice',          true,  true, 'composite'),
('Pav bhaji',                  'पाव भाजी',            'combo',     450, 11.0, 60.0, 18.0, 6.0, 1, 'plate',  '2 pav + bhaji + butter',                       true,  true, 'composite'),
('Dosa sambhar',               'डोसा सांबर',          'combo',     250, 9.5,  38.0, 7.5,  5.5, 1, 'plate',  '1 dosa + sambhar + chutney',                   true,  true, 'composite'),
('Poha plate',                 'पोहा थाली',           'combo',     280, 7.0,  44.0, 9.0,  3.5, 1, 'plate',  '1 plate poha with sev + peanuts',              true,  true, 'composite'),
('Misal pav',                  'मिसल पाव',            'combo',     400, 14.0, 52.0, 15.0, 9.0, 1, 'plate',  '1 plate misal with 2 pav',                     true,  true, 'composite'),
('Idli sambhar',               'इडली सांबर',          'combo',     260, 10.5, 44.0, 4.5,  6.0, 1, 'plate',  '2 idli + sambhar + chutney',                   true,  true, 'composite'),

-- ─────────────────────────────────────────────────────────────────────────────
-- PROTEIN SOURCES  (22)
-- ─────────────────────────────────────────────────────────────────────────────
('Chicken breast grilled',     'ग्रिल्ड चिकन ब्रेस्ट',  'protein',   165, 31.0, 0.0,  3.6,  0.0, 100,'g',     '100g grilled chicken breast',                  false, true, 'IFCT-2017'),
('Chicken thigh',              'चिकन थाई',            'protein',   210, 26.0, 0.0,  11.0, 0.0, 100,'g',     '100g cooked chicken thigh',                    false, true, 'IFCT-2017'),
('Paneer raw',                 'पनीर',                'protein',   265, 18.0, 4.0,  20.0, 0.0, 100,'g',     '100g paneer',                                  false, true, 'IFCT-2017'),
('Tofu',                       'टोफू',                'protein',   76,  8.0,  2.0,  4.5,  0.5, 100,'g',     '100g tofu',                                    false, true, 'IFCT-2017'),
('Soya chunks cooked',         'सोया चंक्स',          'protein',   170, 22.0, 12.0, 3.5,  4.5, 1, 'katori', '1 katori cooked soya chunks',                  false, true, 'IFCT-2017'),
('Egg white',                  'अंडे का सफेद भाग',     'protein',   17,  3.6,  0.2,  0.1,  0.0, 1, 'piece',  '1 egg white',                                  false, true, 'IFCT-2017'),
('Whole egg boiled',           'उबला अंडा',           'protein',   78,  6.3,  0.6,  5.3,  0.0, 1, 'piece',  '1 whole boiled egg',                           false, true, 'IFCT-2017'),
('Fish grilled',               'ग्रिल्ड मछली',        'protein',   130, 22.0, 0.0,  4.5,  0.0, 100,'g',     '100g grilled fish (rohu/basa)',                false, true, 'IFCT-2017'),
('Prawns',                     'झींगा',               'protein',   100, 20.0, 1.0,  1.5,  0.0, 100,'g',     '100g cooked prawns',                           false, true, 'IFCT-2017'),
('Mutton',                     'मटन',                 'protein',   250, 25.0, 0.0,  17.0, 0.0, 100,'g',     '100g cooked mutton',                           false, true, 'IFCT-2017'),
('Whey protein scoop',         'व्हे प्रोटीन',         'protein',   120, 24.0, 3.0,  1.5,  0.0, 30, 'g',     '1 scoop (~30g) whey protein',                  false, true, 'estimate'),
('Greek yogurt',               'ग्रीक दही',           'protein',   130, 17.0, 9.0,  3.0,  0.0, 1, 'cup',    '1 cup (~170g) plain greek yogurt',             false, true, 'estimate'),
('Paneer tikka',               'पनीर टिक्का',         'protein',   200, 17.0, 4.0,  13.0, 1.0, 100,'g',     '100g paneer tikka grilled',                    false, true, 'IFCT-2017'),
('Sprouts',                    'अंकुरित दाल',         'protein',   100, 8.0,  16.0, 0.5,  4.5, 1, 'katori', '1 katori moong sprouts',                       false, true, 'IFCT-2017'),
('Moong dal cooked',           'पकी मूँग दाल',        'protein',   120, 8.5,  20.0, 0.5,  6.0, 1, 'katori', '1 katori cooked moong dal (no tadka)',         false, true, 'IFCT-2017'),
('Chickpeas boiled',           'उबले चने',            'protein',   160, 9.0,  27.0, 2.5,  7.0, 1, 'katori', '1 katori boiled chana',                        false, true, 'IFCT-2017'),
('Peanuts',                    'मूंगफली',             'protein',   170, 7.5,  5.0,  14.0, 2.5, 30, 'g',     '30g (small handful) peanuts',                  false, true, 'IFCT-2017'),
('Curd / Dahi',                'दही',                  'protein',   100, 6.0,  10.0, 4.0,  0.0, 1, 'katori', '1 katori plain curd (~150g)',                  false, true, 'IFCT-2017'),
('Almonds',                    'बादाम',               'protein',   170, 6.0,  6.0,  15.0, 3.0, 30, 'g',     '30g almonds (~22 pieces)',                     false, true, 'IFCT-2017'),
('Cashews',                    'काजू',                'protein',   165, 5.5,  9.0,  13.0, 1.0, 30, 'g',     '30g cashews',                                  false, true, 'IFCT-2017'),
('Walnuts',                    'अखरोट',               'protein',   190, 4.5,  4.0,  18.0, 2.0, 30, 'g',     '30g walnut halves',                            false, true, 'IFCT-2017'),
('Pumpkin seeds',              'कद्दू के बीज',         'protein',   160, 9.0,  4.0,  13.0, 1.5, 30, 'g',     '30g pumpkin seeds',                            false, true, 'estimate'),

-- ─────────────────────────────────────────────────────────────────────────────
-- SNACKS  (28)
-- ─────────────────────────────────────────────────────────────────────────────
('Samosa',                     'समोसा',               'snack',     260, 5.0,  30.0, 13.0, 2.0, 1, 'piece',  '1 medium samosa',                              false, true, 'IFCT-2017'),
('Pakora / Bhajia',            'पकोड़ा',                'snack',     250, 7.0,  24.0, 14.0, 2.5, 5, 'piece',  '5 mixed pakoras',                              false, true, 'IFCT-2017'),
('Vada pav',                   'वड़ा पाव',              'snack',     290, 8.0,  36.0, 13.0, 2.5, 1, 'piece',  '1 vada pav',                                   true,  true, 'IFCT-2017'),
('Kachori',                    'कचौड़ी',                'snack',     200, 5.0,  22.0, 11.0, 1.5, 1, 'piece',  '1 medium kachori',                             false, true, 'IFCT-2017'),
('Bhel puri',                  'भेल पूरी',            'snack',     200, 5.0,  32.0, 6.5,  3.0, 1, 'plate',  '1 plate bhel puri',                            false, true, 'IFCT-2017'),
('Sev puri',                   'सेव पूरी',            'snack',     250, 5.5,  32.0, 11.0, 2.5, 6, 'piece',  '6 sev puris',                                  false, true, 'IFCT-2017'),
('Pani puri',                  'पानी पूरी',           'snack',     180, 4.0,  30.0, 5.0,  2.5, 6, 'piece',  '6 pani puris',                                 false, true, 'IFCT-2017'),
('Dhokla',                     'ढोकला',               'snack',     150, 6.0,  22.0, 4.0,  1.5, 3, 'piece',  '3 pieces khaman dhokla',                       false, true, 'IFCT-2017'),
('Khakhra',                    'खाखरा',               'snack',     120, 4.0,  20.0, 3.0,  2.5, 2, 'piece',  '2 plain khakhras',                             false, true, 'IFCT-2017'),
('Mathri',                     'मठरी',                'snack',     180, 4.0,  20.0, 10.0, 1.0, 3, 'piece',  '3 mathris',                                    false, true, 'IFCT-2017'),
('Namkeen / Mixture',          'नमकीन',                'snack',     200, 5.0,  20.0, 12.0, 2.0, 1, 'bowl',   '1 small bowl namkeen mixture (~40g)',          false, true, 'IFCT-2017'),
('Makhana roasted',            'भुना मखाना',          'snack',     100, 4.0,  20.0, 0.5,  2.5, 1, 'cup',    '1 cup roasted makhana (~30g)',                 false, true, 'IFCT-2017'),
('Peanut chikki',              'मूंगफली चिक्की',      'snack',     120, 4.0,  12.0, 7.0,  1.0, 1, 'piece',  '1 piece peanut chikki (~25g)',                 false, true, 'IFCT-2017'),
('Protein bar',                'प्रोटीन बार',         'snack',     200, 15.0, 22.0, 7.0,  3.0, 1, 'piece',  '1 protein bar (~60g)',                         false, true, 'estimate'),
('Banana',                     'केला',                'snack',     105, 1.3,  27.0, 0.4,  3.0, 1, 'piece',  '1 medium banana',                              false, true, 'IFCT-2017'),
('Apple',                      'सेब',                 'snack',     95,  0.5,  25.0, 0.3,  4.5, 1, 'piece',  '1 medium apple',                               false, true, 'IFCT-2017'),
('Mango',                      'आम',                  'snack',     150, 1.5,  38.0, 0.6,  3.5, 1, 'piece',  '1 medium mango',                               false, true, 'IFCT-2017'),
('Papaya',                     'पपीता',               'snack',     55,  0.9,  14.0, 0.2,  2.5, 1, 'cup',    '1 cup cubed papaya',                           false, true, 'IFCT-2017'),
('Orange',                     'संतरा',               'snack',     65,  1.3,  16.0, 0.2,  3.0, 1, 'piece',  '1 medium orange',                              false, true, 'IFCT-2017'),
('Guava',                      'अमरूद',               'snack',     70,  2.5,  14.0, 0.9,  5.5, 1, 'piece',  '1 medium guava',                               false, true, 'IFCT-2017'),
('Pomegranate',                'अनार',                'snack',     85,  1.5,  20.0, 1.0,  4.0, 0.5,'cup',   '½ cup pomegranate seeds',                      false, true, 'IFCT-2017'),
('Chana jor garam',            'चना जोर गरम',         'snack',     150, 7.0,  22.0, 3.5,  4.5, 1, 'bowl',   '1 small bowl chana jor garam (~40g)',          false, true, 'IFCT-2017'),
('Kurmura / Murmura',          'मुरमुरा',              'snack',     110, 2.0,  24.0, 0.5,  0.5, 1, 'bowl',   '1 bowl plain puffed rice',                     false, true, 'IFCT-2017'),
('Dry fruits mix',             'सूखे मेवे',           'snack',     160, 5.0,  10.0, 12.0, 2.0, 30, 'g',     '30g mixed dry fruits',                         false, true, 'estimate'),
('Dark chocolate',             'डार्क चॉकलेट',        'snack',     100, 1.5,  10.0, 7.0,  2.0, 20, 'g',     '2 squares dark chocolate (~20g)',              false, true, 'estimate'),
('Roasted chana',              'भुना चना',            'snack',     130, 7.0,  22.0, 2.5,  5.0, 30, 'g',     '30g roasted chana',                            false, true, 'IFCT-2017'),
('Aloo tikki',                 'आलू टिक्की',          'snack',     180, 3.0,  22.0, 9.0,  2.0, 1, 'piece',  '1 aloo tikki',                                 false, true, 'IFCT-2017'),
('Cucumber',                   'खीरा',                'snack',     30,  1.0,  6.0,  0.2,  1.5, 1, 'cup',    '1 cup sliced cucumber',                        false, true, 'IFCT-2017'),

-- ─────────────────────────────────────────────────────────────────────────────
-- DRINKS  (22)
-- ─────────────────────────────────────────────────────────────────────────────
('Chai with sugar',            'चाय (चीनी के साथ)',    'drink',     80,  2.5,  10.0, 3.0,  0.0, 1, 'cup',    '1 cup masala chai with sugar',                 false, true, 'estimate'),
('Chai without sugar',         'चाय (बिना चीनी)',     'drink',     30,  2.0,  3.0,  1.5,  0.0, 1, 'cup',    '1 cup chai with milk, no sugar',               false, true, 'estimate'),
('Black coffee',               'ब्लैक कॉफी',          'drink',     5,   0.3,  1.0,  0.0,  0.0, 1, 'cup',    '1 cup black coffee',                           false, true, 'estimate'),
('Coffee with milk',           'दूध वाली कॉफी',        'drink',     60,  3.0,  6.0,  2.5,  0.0, 1, 'cup',    '1 cup coffee with toned milk, no sugar',       false, true, 'estimate'),
('Cold coffee',                'कोल्ड कॉफी',          'drink',     180, 6.0,  26.0, 6.0,  0.0, 1, 'glass',  '1 glass cold coffee with sugar',               false, true, 'estimate'),
('Sweet lassi',                'मीठी लस्सी',          'drink',     200, 6.0,  30.0, 6.0,  0.0, 1, 'glass',  '1 glass sweet lassi',                          false, true, 'IFCT-2017'),
('Salted lassi',               'नमकीन लस्सी',          'drink',     100, 5.0,  8.0,  5.0,  0.0, 1, 'glass',  '1 glass salted lassi',                         false, true, 'IFCT-2017'),
('Chaas / Buttermilk',         'छाछ',                 'drink',     40,  2.5,  4.0,  1.5,  0.0, 1, 'glass',  '1 glass chaas',                                false, true, 'IFCT-2017'),
('Full cream milk',            'फुल क्रीम दूध',       'drink',     160, 8.0,  12.0, 8.0,  0.0, 250,'ml',    '1 glass (250ml) full cream milk',              false, true, 'IFCT-2017'),
('Toned milk',                 'टोन्ड दूध',           'drink',     120, 8.0,  12.0, 4.0,  0.0, 250,'ml',    '1 glass (250ml) toned milk',                   false, true, 'IFCT-2017'),
('Skimmed milk',               'स्किम्ड दूध',         'drink',     90,  8.5,  12.0, 0.5,  0.0, 250,'ml',    '1 glass (250ml) skimmed milk',                 false, true, 'IFCT-2017'),
('Nimbu pani',                 'नींबू पानी',          'drink',     50,  0.2,  13.0, 0.0,  0.0, 1, 'glass',  '1 glass lemonade with sugar',                  false, true, 'estimate'),
('Coconut water',              'नारियल पानी',         'drink',     45,  0.5,  11.0, 0.5,  0.0, 1, 'glass',  '1 glass tender coconut water',                 false, true, 'IFCT-2017'),
('Mango shake',                'आम मिल्क शेक',         'drink',     250, 6.0,  44.0, 6.0,  2.0, 1, 'glass',  '1 glass mango milkshake',                      false, true, 'estimate'),
('Banana shake',               'केला शेक',            'drink',     200, 7.0,  34.0, 5.0,  2.0, 1, 'glass',  '1 glass banana milkshake',                     false, true, 'estimate'),
('Protein shake homemade',     'प्रोटीन शेक',          'drink',     350, 32.0, 38.0, 8.0,  3.0, 1, 'glass',  '1 glass: milk + banana + whey scoop',          true,  true, 'estimate'),
('Sugarcane juice',            'गन्ने का रस',         'drink',     180, 0.5,  45.0, 0.0,  0.0, 1, 'glass',  '1 glass sugarcane juice (~250ml)',             false, true, 'IFCT-2017'),
('ORS / Electral',             'ओआरएस',               'drink',     25,  0.0,  6.0,  0.0,  0.0, 1, 'glass',  '1 glass ORS',                                  false, true, 'estimate'),
('Green tea',                  'ग्रीन टी',            'drink',     2,   0.0,  0.5,  0.0,  0.0, 1, 'cup',    '1 cup green tea, no sugar',                    false, true, 'estimate'),
('Filter coffee',              'फिल्टर कॉफी',         'drink',     90,  3.5,  10.0, 3.5,  0.0, 1, 'cup',    '1 cup South Indian filter coffee with sugar',  false, true, 'estimate'),
('Aam panna',                  'आम पन्ना',            'drink',     110, 0.5,  28.0, 0.2,  0.5, 1, 'glass',  '1 glass aam panna',                            false, true, 'estimate'),
('Jaljeera',                   'जलजीरा',              'drink',     20,  0.5,  4.0,  0.2,  0.5, 1, 'glass',  '1 glass jaljeera',                             false, true, 'estimate'),

-- ─────────────────────────────────────────────────────────────────────────────
-- DESSERTS  (18)
-- ─────────────────────────────────────────────────────────────────────────────
('Gulab jamun',                'गुलाब जामुन',         'dessert',   300, 4.0,  44.0, 12.0, 0.5, 2, 'piece',  '2 pieces gulab jamun in syrup',                false, true, 'IFCT-2017'),
('Rasgulla',                   'रसगुल्ला',            'dessert',   200, 4.5,  40.0, 3.0,  0.0, 2, 'piece',  '2 pieces rasgulla',                            false, true, 'IFCT-2017'),
('Kheer',                      'खीर',                 'dessert',   200, 6.0,  30.0, 6.0,  0.5, 1, 'katori', '1 katori rice kheer',                          false, true, 'IFCT-2017'),
('Suji halwa',                 'सूजी हलवा',           'dessert',   250, 4.0,  34.0, 11.0, 1.0, 1, 'katori', '1 katori suji halwa',                          false, true, 'IFCT-2017'),
('Jalebi',                     'जलेबी',                'dessert',   300, 2.5,  56.0, 8.0,  0.5, 3, 'piece',  '3 pieces jalebi (~75g)',                       false, true, 'IFCT-2017'),
('Besan laddu',                'बेसन लड्डू',          'dessert',   180, 4.0,  20.0, 9.0,  1.5, 1, 'piece',  '1 besan laddu',                                false, true, 'IFCT-2017'),
('Barfi',                      'बर्फी',                'dessert',   150, 3.0,  18.0, 7.0,  0.3, 1, 'piece',  '1 piece milk barfi',                           false, true, 'IFCT-2017'),
('Ice cream',                  'आइसक्रीम',            'dessert',   140, 2.5,  18.0, 7.0,  0.5, 1, 'scoop',  '1 scoop vanilla ice cream',                    false, true, 'estimate'),
('Gajar halwa',                'गाजर हलवा',           'dessert',   280, 5.0,  34.0, 14.0, 2.5, 1, 'katori', '1 katori gajar halwa',                         false, true, 'IFCT-2017'),
('Kulfi',                      'कुल्फी',               'dessert',   160, 4.5,  18.0, 8.0,  0.0, 1, 'piece',  '1 kulfi stick',                                false, true, 'IFCT-2017'),
('Rasmalai',                   'रसमलाई',              'dessert',   220, 6.5,  28.0, 9.0,  0.0, 2, 'piece',  '2 pieces rasmalai',                            false, true, 'IFCT-2017'),
('Moong dal halwa',            'मूँग दाल हलवा',       'dessert',   320, 7.0,  34.0, 17.0, 2.0, 1, 'katori', '1 katori moong dal halwa',                     false, true, 'IFCT-2017'),
('Atta laddu',                 'आटा लड्डू',           'dessert',   200, 4.0,  22.0, 10.0, 1.5, 1, 'piece',  '1 atta laddu',                                 false, true, 'IFCT-2017'),
('Boondi laddu',               'बूंदी लड्डू',          'dessert',   190, 3.0,  24.0, 9.0,  0.8, 1, 'piece',  '1 boondi laddu',                               false, true, 'IFCT-2017'),
('Sandesh',                    'संदेश',               'dessert',   140, 5.0,  18.0, 5.0,  0.0, 1, 'piece',  '1 piece sandesh',                              false, true, 'IFCT-2017'),
('Mysore pak',                 'मैसूर पाक',           'dessert',   200, 2.0,  22.0, 12.0, 0.3, 1, 'piece',  '1 piece mysore pak',                           false, true, 'IFCT-2017'),
('Phirni',                     'फिरनी',               'dessert',   190, 5.0,  28.0, 6.0,  0.3, 1, 'katori', '1 katori phirni',                              false, true, 'IFCT-2017'),
('Shrikhand',                  'श्रीखंड',             'dessert',   210, 7.0,  28.0, 7.0,  0.3, 1, 'katori', '1 katori shrikhand',                           false, true, 'IFCT-2017')
;
